### ISSUE TITLE
Замечания по паттерну "Стратегия"

### ISSUE THREAD

**Issue by alexey-malov** [AnImperialMan/OodLabs#1]
https://github.com/AnImperialMan/OodLabs/blob/ddf6caab4b726955cd23b0006bd64aa629a00c94/Lab1/SimUDuck/Ducks/Duck.cs#L40-L43
https://github.com/AnImperialMan/OodLabs/blob/ddf6caab4b726955cd23b0006bd64aa629a00c94/Lab1/SimUDuckFP/Ducks/Duck.cs#L38-L41
- [x] Метод следует сделать абстрактным

**Comment by AnImperialMan** [comment]
В шарпе абстрактные методы могут быть только в абстрактных классах. В таком случае и класс придется сделать абстрактным.
